### ISSUE TITLE
multiple companions

### ISSUE THREAD

**Issue by gilescope** [paritytech/pipeline-scripts#3]
https://github.com/paritytech/pipeline-scripts/blob/9f2e909fad823eae317f2789aa7b7e4adc8df9ab/check_dependent_project.sh

seems to assume there's only one companion PR but there could be multiple. (polkadot and cumulus)

Also if there are then polkadot is going to want to bu pulled into the cumulus companion build.

UPDATE: multiple companions are supported and refer to each other. It is only the edge case of when there is no cumulus PR and yet there is a substrate PR that is not handled.

**Comment by bkchr** [comment]
This issue exists for multiple companions or also for when there is only a Polkadot companion. The problem is that when we check Cumulus, we don't use the Polkadot companion to replace the Polkadot crates, we only do this for the Substrate crates. The solution for this is rather simple, we should also replace the Polkadot crates using the Polkadot companion branch when checking cumulus. So for the Cumulus companion check of Substrate:

1. Check out Cumulus, either master or the referenced companion branch.
2. Check out Polkadot companion, if there is one specified.
3. Run `cargo update -p sp-io -p polkadot-runtime-common`
4. Run `diener patch -p ${PATH_TO_POLKADOT_CHECKOUT}` inside the cumulus checkout.
5. Run `diener patch -p ${PATH_TO_SUBSTRATE_CHECKOUT}` inside the cumulus checkout.
6. Run the check command.

**Comment by TriplEight** [comment]
@bkchr thanks for the write-up.
Tell me please, what are the chances of having this sort of custom logic for the other new companions? Not a big deal, just a decision point either these actions should be executed within the script or a concrete CI job.
Won't 4 conflict with 5?

**Comment by bkchr** [comment]
> Tell me please, what are the chances of having this sort of custom logic for the other new companions?

What other companions?



> Won't 4 conflict with 5?

No, both are doing things.
