### ISSUE TITLE
Companion approvals isn't checked anymore

### ISSUE THREAD

**Issue by bkchr** [paritytech/pipeline-scripts#6]
With the old companion system we checked that the companion pr is mergable, aka approved and has no conflicts. This is now gone completely and would lead to failing merges.

**Comment by joao-paulo-parity** [comment]
The review verdict can be fetched from the Github GraphQL API

```gql
query { 
  repository(name: "substrate", owner: "paritytech") {
    pullRequest(number: 4550) {
      reviewDecision
    }
  }
}
```

where `reviewDecision` is an enum documented in https://docs.github.com/en/graphql/reference/enums#pullrequestreviewdecision.

More context for this approach and heads-up about potential caveats is given in https://stackoverflow.com/a/66768243/16833094.

Right now we do not have GraphQL capabilities for the script. Hopefully using the Github token for GraphQL is [as easy as it is for REST](https://github.com/paritytech/pipeline-scripts/blob/59cda1965797c94337c6f7d952227b5fc5c51508/check_dependent_project.sh#L211).

**Comment by joao-paulo-parity** [comment]
Revisiting this issue.

I don't know if this script should check for approvals.

[parity-processbot already checks for the pr-custom-review](https://github.com/paritytech/parity-processbot/blob/2a17d9936f2c87e7f5b2c089b0c6719d988e7755/src/companion.rs#L525) which is **required on GitHub repository settings** anyways so having the check in this script doesn't add anything.

@bkchr do you have an argument for also having the approvals check in this script in addition to the other places mentioned above? Otherwise I think we can close this issue

**Comment by bkchr** [comment]
The point is that you need to check in Substrate CI that the Polkadot pr is reviewed. You are right that these tools check the review status, but you don't want that a companion is merged in Substrate and then it stops because there are reviews missing in Polkadot.

**Comment by mordamax** [comment]
@bkchr I don't probably fully understand what you mean. AFAIK processbot won't merge substrate part until polkadot is reviewed, when you type `bot merge`, and this has nothing to do with pipeline-script, as merge is responsibility of process-bot, not pipeline scripts, which checks the compatibility, not the statuses.
Could you please elaborate?

**Comment by bkchr** [comment]
As I said in the description, in the old companion system it was checked that the pr is approved. However, as the bot is now able to merge companions, it is not really required anymore. Going to close the issue.
